### ISSUE TITLE
"Syntax Error: Expected Name, found String \"loc\""

### ISSUE THREAD

**Issue by denisbarboni** [markshust/docker-magento#1258]
Hello Guys, 

After I updated to version 2.4.7-p3, all graphql api's started returning the following error:

<img width="568" alt="image" src="https://github.com/user-attachments/assets/d67b9d1c-0015-419f-b775-df45576b7d80">

**Exception Log:**

```
[2024-11-28T21:23:02.091452+00:00] report.CRITICAL: GraphQL\Error\SyntaxError: Syntax Error: Expected Name, found String "loc" in /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php:382
Stack trace:
#0 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(494): GraphQL\Language\Parser->expect('Name')
#1 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(741): GraphQL\Language\Parser->parseName()
#2 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(731): GraphQL\Language\Parser->parseField()
#3 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(713): GraphQL\Language\Parser->parseSelection()
#4 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(478): GraphQL\Language\Parser->GraphQL\Language\{closure}(Object(GraphQL\Language\Parser))
#5 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(711): GraphQL\Language\Parser->many('{', Object(Closure), '}')
#6 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(603): GraphQL\Language\Parser->parseSelectionSet()
#7 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(582): GraphQL\Language\Parser->parseOperationDefinition()
#8 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(554): GraphQL\Language\Parser->parseExecutableDefinition()
#9 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(515): GraphQL\Language\Parser->parseDefinition()
#10 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(478): GraphQL\Language\Parser->GraphQL\Language\{closure}(Object(GraphQL\Language\Parser))
#11 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(513): GraphQL\Language\Parser->many('<SOF>', Object(Closure), '<EOF>')
#12 /var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php(193): GraphQL\Language\Parser->parseDocument()
#13 /var/www/html/vendor/magento/framework/GraphQl/Query/QueryParser.php(36): GraphQL\Language\Parser::parse(Object(GraphQL\Language\Source))
#14 /var/www/html/vendor/magento/framework/GraphQl/Query/QueryProcessor.php(83): Magento\Framework\GraphQl\Query\QueryParser->parse('{"loc":{"start"...')
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\GraphQl\Query\QueryProcessor->process(Object(Magento\Framework\GraphQl\Schema), '{"loc":{"start"...', Object(Magento\GraphQl\Model\Query\Context), Array, NULL)
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\GraphQl\Query\QueryProcessor\Interceptor->___callParent('process', Array)
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\GraphQl\Query\QueryProcessor\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\GraphQl\Schema), Object(GraphQL\Language\AST\DocumentNode), Object(Magento\GraphQl\Model\Query\Context), Array)
#18 /var/www/html/generated/code/Magento/Framework/GraphQl/Query/QueryProcessor/Interceptor.php(23): Magento\Framework\GraphQl\Query\QueryProcessor\Interceptor->___callPlugins('process', Array, Array)
#19 /var/www/html/vendor/magento/module-graph-ql/Controller/GraphQl.php(202): Magento\Framework\GraphQl\Query\QueryProcessor\Interceptor->process(Object(Magento\Framework\GraphQl\Schema), Object(GraphQL\Language\AST\DocumentNode), Object(Magento\GraphQl\Model\Query\Context), Array)
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\GraphQl\Controller\GraphQl->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\GraphQl\Controller\GraphQl\Interceptor->___callParent('dispatch', Array)
#22 /var/www/html/vendor/fastly/magento2/Model/FrontControllerPlugin.php(128): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\GraphQl\Controller\GraphQl\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(76): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\GraphQl\Controller\GraphQl\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/generated/code/Magento/GraphQl/Controller/GraphQl/Interceptor.php(23): Magento\GraphQl\Controller\GraphQl\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\GraphQl\Controller\GraphQl\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#31 /var/www/html/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))
#33 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#34 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, NULL)
#35 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#36 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#37 {main}
```

Anyone else having the same problem?

**Comment by kpatidar37** [comment]
Hi Guys, 

Did anyone find solution to this problem, we are running into same. 

{
  "errors": [
    {
      "message": "Syntax Error: Expected Name, found String \"loc\"",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ],
      "extensions": {
        "file": "/var/www/html/vendor/webonyx/graphql-php/src/Language/Parser.php",
        "line": 382
      }
    }
  ]
}

**Comment by Bar3nho** [comment]
@kpatidar37 @denisbarboni 
In case anyone stumbles upon this issue - in Magento 2.4.7 there was a change in:
`\Magento\Framework\GraphQl\Query\QueryProcessor::process`
2.4.7-p4 version:
```
public function process(
        Schema $schema,
        DocumentNode|string $source,
        ContextInterface $contextValue = null,
        array $variableValues = null,
        string $operationName = null
    ): array {
```
previous Magento versions:
```
public function process(
        Schema $schema,
        string $source,
        ContextInterface $contextValue = null,
        array $variableValues = null,
        string $operationName = null
    ): array {
```
Now instead of `string $source`, the function allows `DocumentNode|string $source`.

If you have any plugins hooked onto this method, they may cause the error  `"Syntax Error: Expected Name, found String "loc". `
Refactoring my plugins helped fix this problem.
