### ISSUE TITLE
"gzip: stdin: Unexpected end of file" when extracting magento2-2.4.1.tar.gz to ./src

### ISSUE THREAD

**Issue by OleksiiBulba** [markshust/docker-magento#365]
**Description**
I setup the project on a fresh Ubutu installation and got an error
`gzip: stdin: unexpected end of file`.
I suppose script cannot download tar.gz archive.

**Steps To Reproduce**
1. Install VirtualBox;
2. Download Ubuntu 20.04 iso;
3. Create VM (30Gb hard drive, 4Gb RAM), add iso to it;
4. Start VM, install Linux without any additional software (no libreoffice etc.) and with all updates;
5. Allow Ubuntu install latest updates, restart VM;
6. Install docker, docker-compose, PHPStorm, virtualbox guest additions, make, npm, yarn; restart VM;
7. Run `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.4.1`

**Expected Result**
Magento store is accessible by https://magento2.test/

**Actual Result**
Store is not accessble: `Unable to connect` Firefox browser error
Console output:
```
oleksii@oleksii-dev:~/projects/magento2$ curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.4.1
Initialized empty Git repository in /home/oleksii/projects/magento2/.git/
Extracting magento2-2.4.1.tar.gz to ./src

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Your system password has been requested to add an entry to /etc/hosts...
127.0.0.1 ::1 magento2.test
Creating network "magento2_default" with the default driver
Creating volume "magento2_appdata" with default driver
Creating volume "magento2_dbdata" with default driver
Creating volume "magento2_rabbitmqdata" with default driver
Creating volume "magento2_sockdata" with default driver
Creating volume "magento2_ssldata" with default driver
Pulling db (percona:5.7)...
5.7: Pulling from library/percona
7a0437f04f83: Pull complete
... 4 similar lines skipped ...
dcc7f9b3a007: Pull complete
Digest: sha256:358eff0fa5115958da5e913c56f6420cfe5a2102dde63f8b06bbc24566893916
Status: Downloaded newer image for percona:5.7
Pulling phpfpm (markoshust/magento-php:7.4-fpm-2)...
7.4-fpm-2: Pulling from markoshust/magento-php
bb79b6b2107f: Pull complete
... 27 similar lines skipped ...
800ec7786ebc: Pull complete
Digest: sha256:8c39d0f38d02ba3fb1084189c00b0c3e7142e718f405a4d6f995b798a909a0c0
Status: Downloaded newer image for markoshust/magento-php:7.4-fpm-2
Pulling app (markoshust/magento-nginx:1.18-4)...
1.18-4: Pulling from markoshust/magento-nginx
cbdbe7a5bc2a: Pull complete
... 13 similar lines skipped ...
1bc1c96bbca8: Pull complete
Digest: sha256:7cf78ecc2cab949a9d911fd8be7c6a601b6b8af4a3660ab7d17a09d56bf52b2f
Status: Downloaded newer image for markoshust/magento-nginx:1.18-4
Pulling redis (redis:5.0-alpine)...
5.0-alpine: Pulling from library/redis
801bfaa63ef2: Pull complete
... 4 similar lines skipped ...
188cd588ab68: Pull complete
Digest: sha256:cab1de051c243a956749397af796d50bf235c7183e88bc4667259f66cad4f748
Status: Downloaded newer image for redis:5.0-alpine
Pulling elasticsearch (markoshust/magento-elasticsearch:7.6.2-2)...
7.6.2-2: Pulling from markoshust/magento-elasticsearch
ab5ef0e58194: Pull complete
... 7 similar lines skipped ...
587cf06e9307: Pull complete
Digest: sha256:4302ebdced3fade990ccdf892474d99167add17f630a9cd0448cd55e7514fd6a
Status: Downloaded newer image for markoshust/magento-elasticsearch:7.6.2-2
Pulling rabbitmq (rabbitmq:3.7-management-alpine)...
3.7-management-alpine: Pulling from library/rabbitmq
df20fa9351a1: Pull complete
... 7 similar lines skipped ...
4012d1250c55: Pull complete
Digest: sha256:e97f6bb68aab3f747f8a6f4dc52ed57401de91ca480a0be3a36e7476ac273169
Status: Downloaded newer image for rabbitmq:3.7-management-alpine
Creating magento2_elasticsearch_1 ... done
Creating magento2_rabbitmq_1      ... done
Creating magento2_db_1            ... done
Creating magento2_redis_1         ... done
Creating magento2_phpfpm_1        ... done
Creating magento2_app_1           ... done
Copying all files from host to container...
Completed copying all files from host to container
Correcting filesystem ownerships...
Filesystem ownerships corrected.
Correcting filesystem permissions...
find: 'var': No such file or directory
find: 'vendor': No such file or directory
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory
find: 'app/etc': No such file or directory
chmod: cannot access 'bin/magento': No such file or directory
Filesystem permissions corrected.
chmod: cannot access 'bin/magento': No such file or directory

    Authentication required (repo.magento.com, public_key and private_key):
        Username: <public key entered>
        Password: <private key entered>

Authentication will add to host composer global config (/home/oleksii/.composer/auth.json) for docekr container
mv: cannot stat '/home/oleksii/.composer/auth.json': No such file or directory
cat: /home/oleksii/.composer/auth.json.bak: No such file or directory
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Success to setup composer auth
Forcing reinstall of composer deps to ensure perms & reqs...

                                                                          
  [Seld\JsonLint\ParsingException]                                        
  "/var/www/.composer/auth.json" does not contain valid JSON              
  Parse error on line 1:                                                  
                                                                          
  ^                                                                       
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  
                                                                          

global <command-name> [<args>]...


                                                                          
  [Seld\JsonLint\ParsingException]                                        
  "/var/www/.composer/auth.json" does not contain valid JSON              
  Parse error on line 1:                                                  
                                                                          
  ^                                                                       
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  
                                                                          

OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
Turning on developer mode..
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
Forcing deploy of static content to speed up initial requests...
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
Re-indexing with Elasticsearch...
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
Clearing the cache to apply updates...
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
Copying files from container to host after install...
Error: No such container:path: b84584b94e6bd80c0513622bb9d152166639f886872f8ff48891fa9a280eaa4a:/var/www/html/app
Completed copying app from container to host
Error: No such container:path: b84584b94e6bd80c0513622bb9d152166639f886872f8ff48891fa9a280eaa4a:/var/www/html/vendor
Completed copying vendor from container to host
Generating SSL certificate...
cat: can't open '/root/.local/share/mkcert/rootCA.pem': No such file or directory
Created a new local CA at "/root/.local/share/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️

System password requested to install certificate authority on host...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Using the local CA at "/root/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "magento2.test"

The certificate is at "nginx.crt" and the key at "nginx.key" ✅

Moving key and cert to /etc/nginx/certs/...
Restarting containers to apply updates...
Stopping magento2_app_1           ... done
Stopping magento2_phpfpm_1        ... done
Stopping magento2_db_1            ... done
Stopping magento2_redis_1         ... done
Stopping magento2_elasticsearch_1 ... done
Stopping magento2_rabbitmq_1      ... done
./src/app/design: No such file or directory
./src/app/etc: No such file or directory
./src/composer.json: No such file or directory
./src/composer.lock: No such file or directory
./src/nginx.conf.sample: No such file or directory
Failed to start docker for missing volume files
Docker development environment setup complete.
You may now access your Magento instance at https://magento2.test/
```

**Comment by OleksiiBulba** [comment]
One of the way to bypass the issue:
`rm ~./docker-magento/*`
and start again.

**Comment by markshust** [comment]
Hi @OleksiiBulba - yes it appears your initial download failed at some point. Unfortunately there is no way to really detect this on a subsequent install, and your resolution is the correct fix. 

I don't think there is anything left to do here, so will close out this ticket.
