### ISSUE TITLE
Error with Mailhog on Apple M1 Silicon

### ISSUE THREAD

**Issue by walkwizus** [markshust/docker-magento#433]
Hi !

**Description**
There are an error with Mailhog on Apple M1 Silicon:

**Steps To Reproduce**
1. Send an email

**Actual Result**
```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x244d90, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x78
runtime.newosproc(0x10526000, 0x10535fe0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x180
runtime.newm(0x284e98, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x12c
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x24
runtime.systemstack(0x32e500)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x105207ac sp=0x105207a8
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x5c fp=0x105207d4 sp=0x105207ac
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:990 +0x4 fp=0x105207d4 sp=0x105207d4
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x244d90, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x78
runtime.newosproc(0x10526000, 0x10535fe0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x180
runtime.newm(0x284e98, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x12c
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x24
runtime.systemstack(0x32e500)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x105207ac sp=0x105207a8
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x5c fp=0x105207d4 sp=0x105207ac
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:990 +0x4 fp=0x105207d4 sp=0x105207d4
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x244d90, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x78
runtime.newosproc(0x10526000, 0x10535fe0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x180
runtime.newm(0x284e98, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x12c
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x24
runtime.systemstack(0x32e500)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x105207ac sp=0x105207a8
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x5c fp=0x105207d4 sp=0x105207ac
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:990 +0x4 fp=0x105207d4 sp=0x105207d4
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x244d90, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x78
runtime.newosproc(0x10526000, 0x10535fe0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x180
runtime.newm(0x284e98, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x12c
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x24
runtime.systemstack(0x32e500)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x105207ac sp=0x105207a8
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x5c fp=0x105207d4 sp=0x105207ac
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:990 +0x4 fp=0x105207d4 sp=0x105207d4
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x244d90, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x78
runtime.newosproc(0x10526000, 0x10535fe0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x180
runtime.newm(0x284e98, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x12c
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x24
runtime.systemstack(0x32e500)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x105207ac sp=0x105207a8
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x5c fp=0x105207d4 sp=0x105207ac
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:990 +0x4 fp=0x105207d4 sp=0x105207d4
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x244d90, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x78
runtime.newosproc(0x10526000, 0x10535fe0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x180
runtime.newm(0x284e98, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x12c
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x24
runtime.systemstack(0x32e500)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:247 +0x80
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x105207ac sp=0x105207a8
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x5c fp=0x105207d4 sp=0x105207ac
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_arm.s:990 +0x4 fp=0x105207d4 sp=0x105207d4
```

So I've replaced MailHog to Mailcatcher. To install it should add in PHP Dockerfile:

```
RUN apt-get install -y msmtp mailutils
COPY conf/msmtprc /etc/msmtprc
```

In images/conf/msmtprc:

```
account default
host mailcatcher
port 1025
from "user@domain.com"

```
Change sendmail_path in php.ini:

`
sendmail_path=/usr/bin/msmtp -t
`

To use Mailcatcher, add this lines in docker-compose.dev.yml:

```
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
```

**Comment by markshust** [comment]
Thank you for this report. I think we should keep this ticket open for a little while. Mailcatcher seems a bit more dated than Mailhog, and I have a feeling a lot of updates will still be made to D4M for Apple silicone support, as it's still the early days of supporting those chips.

Thank you much for the provided workaround. I don't want to replace Mailhog with Mailcatcher at this moment, but definitely will if this isn't supported in M1/M2 chips in a timely manner. Once the second version of this chip comes out, I'd aim for 100% support for the new Apple silicone, especially since I'm sure I'll be jumping on board with them 😄

**Comment by walkwizus** [comment]
Yes you're right. It's just an alternative to catch up email as long as Mailhog is not updated, I also prefer Mailhog ^^.

**Comment by markshust** [comment]
Going to close this in favor of https://github.com/markshust/docker-magento/issues/396 -- would like Apple silicone support across the board. I wonder if the solution to mailhog lies in that ticket.
