### ISSUE TITLE
Run bin/setup-pwa-studio magento.test cannot be completed on win 10 OS WSL 2 Ubuntu

### ISSUE THREAD

**Issue by refaelgold** [markshust/docker-magento#434]
Hey , Im trying to create an PWA app with custom  M2 instance inside docker for a serval hours but I1 cant get any progress . 

I'm running the command : bin/setup-pwa-studio magento.test but im getting a serval errors inside the process and i will  be glad for some advices how to solve my issue 

~/docker-magento$ **bin/setup-pwa-studio magento.test**
Install NodeJS and Yarn on host machine, otherwise setup will fail
Cloning into 'pwa-studio'...
remote: Enumerating objects: 1423, done.
remote: Counting objects: 100% (1423/1423), done.
remote: Compressing objects: 100% (874/874), done.
remote: Total 41321 (delta 634), reused 807 (delta 416), pack-reused 39898
Receiving objects: 100% (41321/41321), 32.54 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (26993/26993), done.
**00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'**

For solving the first issue I did manually clone of PWA repo from compose/bin/setup-pwa-studio Bash file and and take the url repo and try get progress with solution. 

I run the following commands:
**bin/bash**
BASE_URL=${1:-master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud}
git clone https://github.com/magento/pwa-studio.git
**yarn install** 
and then Im running yarn buildpack and i get an issue with ssl(i think). 
 **yarn buildpack create-custom-origin packages/venia-concept**
     at LinuxPlatform.deleteProtectedFiles (/var/www/html/pwa-studio/node_modules/devcert/dist/platforms/linux.js:99:17)
$ /var/www/html/pwa-studio/node_modules/.bin/buildpack create-custom-origin packages/venia-concept
     at uninstall (/var/www/html/pwa-studio/node_modules/devcert/dist/certificate-authority.js:124:25)
Please enter the password for app on f0cc157fce9b.
     at Object.<anonymous> (/var/www/html/pwa-studio/node_modules/devcert/dist/certificate-authority.js:18:9)
     Error: spawnSync sudo ENOENT
     at Generator.next (<anonymous>)
     at Object.spawnSync (internal/child_process.js:1067:20)
     at /var/www/html/pwa-studio/node_modules/tslib/tslib.js:115:75
     at spawnSync (child_process.js:602:24)
     at new Promise (<anonymous>)
     at Object.execFileSync (child_process.js:629:15)
     at Object.__awaiter (/var/www/html/pwa-studio/node_modules/tslib/tslib.js:111:16)
     at Object.run (/var/www/html/pwa-studio/node_modules/devcert/dist/utils.js:22:28)
     at Object.installCertificateAuthority [as default]
     (/var/www/html/pwa-studio/node_modules/devcert/dist/**certificate-authority.js**:16:20)t/dist/platforms/linux.js:99:17)

     at Object.<anonymous> (/var/www/html/pwa-studio/node_modules/devcert/dist/index.js:55:50):124:25)

     at Generator.next (<anonymous>)/html/pwa-studio/node_modules/devcert/dist/c**ertificate-authority.js:18:9)**

After running bin/setup-ssl magento.test - Im still get the same error.

 **bin/setup-ssl magento.test**
Using the local CA at "/root/.local/share/mkcert" ✨
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Created a new certificate valid for the following names 📜
 - "magento.test"awaiter (/var/www/html/pwa-studio/node_modules/tslib/tslib.js:111:16)

The certificate is at "nginx.crt" and the key at "nginx.key" ✅
     (/var/www/html/pwa-studio/node_modules/devcert/dist/certificate-authority.js:16:20)
Moving key and cert to /etc/nginx/certs/...
Restarting containers to apply updates.../pwa-studio/node_modules/devcert/dist/index.js:55:50)

If there is any solution for using  M2  local instance for PWA app inside WIN 10 WSL V2 - I  will be glad to know how to implement it . Maybe there is no solution for that and I will be forced to use a remote server for dev or buy a MacBook :D

**Comment by EmperorKonstantin** [comment]
While i do not have an answer for you, and have given up on WSL2 development entirely, [VSCode Remote SSH development](https://code.visualstudio.com/docs/remote/ssh) could be a life-saver for you. Pair it with an [Intel NUC](https://www.newegg.com/intel-bxnuc10i7fnk1/p/N82E16856102228) and an Samsung NVME SSD Drive that has Ubuntu installed directly on it and stuff it into your desk drawer or near your router.

**Comment by markshust** [comment]
Are you still having this issue? I actually think it may be best to even remove this helper script and run PWA Studio code locally. I just ran this last week on mac and everything went very smooth. I'm not convinced we need to run these node apps through Docker.

**Comment by markshust** [comment]
I'm going to close this out, as this is a very old ticket, on PWA Studio (doesn't have traction at the moment) and on Windows (which I'm not running). If there are still issues running this, please create a new ticket. Note that we don't have official Windows support, but I'm very open to taking any PRs to improve this (but won't be resolving any issues with Windows in the meantime).
