### ISSUE TITLE
/var/www/.composer 目录没有写权限导致Composer auth.json创建失败

### ISSUE THREAD

**Issue by yaohp** [markshust/docker-magento#498]
**Description**
使用的镜像是：markoshust/magento-php:7.4-fpm-6
```
$ curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2
Initialized empty Git repository in /home/develop/magento/.git/
Creating volume "magento_appdata" with default driver
Creating volume "magento_dbdata" with default driver
Creating volume "magento_rabbitmqdata" with default driver
Creating magento_db_1            ... done
Creating volume "magento_ssldata" with default driver
Creating magento_phpfpm_1        ... done
Creating magento_redis_1         ... 
Creating magento_app_1           ... done
Creating magento_elasticsearch_1 ... 
Creating magento_rabbitmq_1      ... done
Creating magento_app_1           ... 

Composer authentication required (repo.magento.com public and private keys):
    Username: ae4ec28eaa737a0995062eff32edfxxx
    Password: 94aed490760f1c8c1a3e51f25bad5xxx

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.18.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 124, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 467, in exec_command
    pty.start()
  File "/usr/lib/python3.6/site-packages/dockerpty/pty.py", line 334, in start
    self._hijack_tty(pumps)
  File "/usr/lib/python3.6/site-packages/dockerpty/pty.py", line 361, in _hijack_tty
    with tty.Terminal(self.operation.stdin, raw=self.operation.israw()):
  File "/usr/lib/python3.6/site-packages/dockerpty/tty.py", line 80, in __enter__
    self.start()
  File "/usr/lib/python3.6/site-packages/dockerpty/tty.py", line 107, in start
    if os.isatty(self.fd.fileno()) and self.israw():
AttributeError: 'NoneType' object has no attribute 'fileno'
Composer auth has been setup.
Creating a "magento/project-community-edition=2.4.2" project at "./"
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

                                                                             
  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  
                                                                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

**Steps To Reproduce**
1.  进入到容器里面查看文件夹权限为root
```
app@0f9e6489ff1e:~/html$ ls -al /var/www 
total 24
drwxr-xr-x 6 app  app  4096 Jul 28 09:23 .
drwxr-xr-x 1 root root 4096 Jul 22 01:36 ..
drwxr-xr-x 2 root root 4096 Jul 28 09:23 .composer
drwxr-xr-x 2 app  app  4096 Jul 27 21:37 .config
drwxr-xr-x 2 app  app  4096 Jul 27 21:37 .npm
drwxr-sr-x 2 app  app  4096 Oct 15  2020 html```

**Expected Result**


**Actual Result**

**Comment by markshust** [comment]
I'm unable to replicate this.

**Comment by stevelou2** [comment]
你怎么搞得,我的默认权限正确:
``drwxr-xr-x`  7 app  app  4096 Jul 29 18:49 .
drwxr-xr-x  1 root root 4096 Jul 22 01:36 ..
-rw-------  1 app  app   187 Jul 29 18:49 .bash_history
drwxr-xr-x  3 app  app  4096 Mar  3 17:21 .composer
drwxr-xr-x  3 app  app  4096 Jul 28 18:33 .composer-global
drwxr-xr-x  2 app  app  4096 Jul 27 21:37 .config
drwxr-xr-x  2 app  app  4096 Jul 27 21:37 .npm
drwxr-sr-x 12 app  app  4096 Jul 28 18:33 html`

**Comment by rangerz** [comment]
@stevelou2 中文可能只有我看得懂...
Its issue is the permission for `~/.composer`the folder
```bash
# correct .composer owner
chown -R $(whoami) ~/.composer

# and then try reinstall again
```

Ref: https://stackoverflow.com/questions/35874482/cannot-create-cache-directory-or-directory-is-not-writable-proceeding-withou

Good Luck

**Comment by markshust** [comment]
Yea, `composer` should never be owned by `root`. Since this is not an issue with this repo, I'll be closing this one out.
