### ISSUE TITLE
PWA Studio Install Error: "magento-venia-concept-gghg-.local.pwadev" is not a valid domain name.

### ISSUE THREAD

**Issue by deedy-tech** [markshust/docker-magento#777]
**Description**
When installing PWA Studio, the process fails with the error 

Error: "magento-venia-concept-gghg-.local.pwadev" is not a valid domain name.

**Steps To Reproduce**
1. Install docker-magento with version 2.4.5
2. Install Sample Data
3. Install PWA Studio with the command - bin/setup-pwa-studio magento-pwa.test

**Expected Result**
Install process completes successfully and PWA Studio is fully installed

**Actual Result**
$ node scripts/monorepo-introduction.js
Preparing packages...
Ensuring valid environment...
✨  Done in 71.16s.
yarn run v1.22.19
$ /Users/rob/Sites/magento-pwa/pwa-studio/node_modules/.bin/buildpack create-custom-origin packages/venia-concept
Creating a local development domain requires temporary administrative privileges.
Please enter the password for rob on robs-mbp-2.local.
  ⓧ  [pwa-buildpack:Utilities:configureHost.js] Could not setup development domain:
     Error: "magento-venia-concept-gghg-.local.pwadev" is not a valid domain name.

     at Object.<anonymous> (/Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/dist/index.js:39:19)

     at Generator.next (<anonymous>)

     at /Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/node_modules/tslib/tslib.js:115:75

     at new Promise (<anonymous>)

     at Object.__awaiter (/Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/node_modules/tslib/tslib.js:111:16)

     at Object.certificateFor (/Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/dist/index.js:34:20)

     at /Users/rob/Sites/magento-pwa/pwa-studio/packages/pwa-buildpack/lib/Utilities/configureHost.js:95:47

     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ⓧ  Error: [pwa-buildpack:Utilities:configureHost.js] Could not setup development domain:
     Error: "magento-venia-concept-gghg-.local.pwadev" is not a valid domain name.

     at Object.<anonymous> (/Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/dist/index.js:39:19)

     at Generator.next (<anonymous>)

     at /Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/node_modules/tslib/tslib.js:115:75

     at new Promise (<anonymous>)

     at Object.__awaiter (/Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/node_modules/tslib/tslib.js:111:16)

     at Object.certificateFor (/Users/rob/Sites/magento-pwa/pwa-studio/node_modules/devcert/dist/index.js:34:20)

     at /Users/rob/Sites/magento-pwa/pwa-studio/packages/pwa-buildpack/lib/Utilities/configureHost.js:95:47

     at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by markshust** [comment]
I don't think this is an issue with docker-magento so closing this one out.
