### ISSUE TITLE
Update version constraints to match current Magento system requirements

### ISSUE THREAD

**Issue by gmonseur** [markshust/docker-magento#994]
Hi,
With an existing installation of Magento ver. 2.4.3-p1 with elasticsearch 7.16.3 (and also 7.9.3), the products in the catalogues are not displayed on frontend. I get this error by trying the following command:
`bin/magento indexer:reindex catalogsearch_fulltext -vvv ` 
results:
```
Unknown 400 error from Elasticsearch null
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /var/www/html/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /var/www/html/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest('HEAD', '/_product_2_v1', Array, NULL, Array, Object(Elasticsearch\Transport))
#7 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(43): Elasticsearch\Transport->performRequest('HEAD', '/_product_2_v1', Array, NULL, Array)
#8 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(289): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest(Object(Elasticsearch\Endpoints\Indices\Exists), Object(Elasticsearch\Transport))
#9 /var/www/html/vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php(270): Elasticsearch\Namespaces\IndicesNamespace->exists(Array)
#10 /var/www/html/vendor/magento/module-elasticsearch/Model/Adapter/Elasticsearch.php(350): Magento\Elasticsearch7\Model\Client\Elasticsearch->indexExists('_product_2_v1')
#11 /var/www/html/vendor/magento/module-elasticsearch/Model/Adapter/Elasticsearch.php(236): Magento\Elasticsearch\Model\Adapter\Elasticsearch->checkIndex('2', 'product', true)
#12 /var/www/html/vendor/magento/module-elasticsearch/Model/Indexer/IndexStructure.php(45): Magento\Elasticsearch\Model\Adapter\Elasticsearch->cleanIndex('2', 'product')
#13 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/IndexStructure.php(70): Magento\Elasticsearch\Model\Indexer\IndexStructure->delete('product', Array)
#14 /var/www/html/vendor/magento/module-elasticsearch/Model/Indexer/IndexerHandler.php(147): Magento\CatalogSearch\Model\Indexer\IndexStructure->delete('product', Array)
#15 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(174): Magento\Elasticsearch\Model\Indexer\IndexerHandler->cleanIndex(Array)
#16 /var/www/html/generated/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Interceptor.php(32): Magento\CatalogSearch\Model\Indexer\Fulltext->executeByDimensions(Array, NULL)
#17 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(235): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->executeByDimensions(Array)
#18 [internal function]: Magento\CatalogSearch\Model\Indexer\Fulltext->Magento\CatalogSearch\Model\Indexer\{closure}()
#19 /var/www/html/vendor/magento/module-indexer/Model/ProcessManager.php(88): call_user_func(Object(Closure))
#20 /var/www/html/vendor/magento/module-indexer/Model/ProcessManager.php(75): Magento\Indexer\Model\ProcessManager->simpleThreadExecute(Array)
#21 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(238): Magento\Indexer\Model\ProcessManager->execute(Array)
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Model\Indexer\Fulltext->executeFull()
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->___callParent('executeFull', Array)
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->Magento\Framework\Interception\{closure}()
#25 /var/www/html/generated/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Interceptor.php(41): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->___callPlugins('executeFull', Array, Array)
#26 /var/www/html/vendor/magento/module-indexer/Model/Indexer.php(443): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->executeFull()
#27 /var/www/html/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(259): Magento\Indexer\Model\Indexer->reindexAll()
#28 /var/www/html/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(110): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#29 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->___callParent('run', Array)
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/generated/code/Magento/Indexer/Console/Command/IndexerReindexCommand/Interceptor.php(86): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->___callPlugins('run', Array, Array)
#34 /var/www/html/vendor/symfony/console/Application.php(1009): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#39 {main}
```

It seems to be an index name error ?
```
bin/cli curl -XGET 'elasticsearch:9200/_product_2_v1'
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_product_2_v1], must not start with '_'.","index_uuid":"_na_","index":"_product_2_v1"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_product_2_v1], must not start with '_'.","index_uuid":"_na_","index":"_product_2_v1"},"status":400}% 
```
I don't know how to correct this.
Can you help me?
Gregory

**Comment by piotrkwiecinski** [comment]
Based on the documentation I reckon you have to use newer version of elasticsearch. https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

It should be 7.17 or 8.5 or opensearch 2.5.

@markshust we'll need to add elasticsearch images 8.5 and 8.7 to be futureproof. Right now we have updated only opensearch.

**Comment by markshust** [comment]
@piotrkwiecinski is Elasticsearch still officially supported by Adobe/Magento? Based on that link, it doesn't appear to be.

**Comment by piotrkwiecinski** [comment]
@markshust yes it is on-premise. It's not supported on the cloud due to the license.
![screenshot-experienceleague adobe com-2023 12 30-19_54_58](https://github.com/markshust/docker-magento/assets/2151333/06ba3d39-c720-4310-b1f0-4242832102d0)

**Comment by markshust** [comment]
@piotrkwiecinski ah thanks, I didn't even see that tab! I think the on-premise tab should probably be the default, as the current tab highlighted can definitely lead to some confusion. Will update 👍
